### ISSUE TITLE
Load modules on `new` instead of on `register`

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-themable-mixin#13]
If we compute and inject modules when the component is created, we can achieve importing theme modules after the element. Also we could load other themes before a new instance of the element is created.

As a bonus, we could have a method for reloading theme modules in the component (might be overriding updateStyles)

**Comment by platosha** [comment]
It would be great, but AFAIK ShadyCSS is, currently, a blocker for this. Polymer’s polyfills collect and transpile styles on register time, the styles added later are not picked up.
