### ISSUE TITLE
Chrome 61 has a deprecation warning for stylesheets inside HTML imports

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-themable-mixin#14]
_From @jouni on September 2, 2017 19:29_

The following message is printed in the console for the themes demos:

     [Deprecation] Styling master document from stylesheets defined in HTML Imports is 
     deprecated, and is planned to be removed in M65, around March 2018. Please refer 
     to https://goo.gl/EGXzpw for possible migration paths.

The details: [https://goo.gl/EGXzpw](https://goo.gl/EGXzpw)

This affects all shared styles in the themes, such as `typography.html`, `color.html`, `sizing-and-spacing` and  `style.html`.

Polymer has an issue regarding this, and hopefully, that will solve the issue for us: https://github.com/Polymer/polymer/issues/4679

_Copied from original issue: vaadin/vaadin-themes#50_

**Comment by tomivirkki** [comment]
Decided to live with the warning for now. According to the message, it should no longer be shown after "around March 2018"

**Comment by samie** [comment]
Running Chrome 66 still getting the warning.

**Comment by lulzimfazlija** [comment]
anyone fixed this?
