### ISSUE TITLE
1.2.0 - Speed regression

### ISSUE THREAD

**Issue by moderndeveloperllc** [vaadin/vaadin-themable-mixin#17]
It appears that v1.2.0 has created a major speed regression when adding lots of items to an element like `vaadin-combo-box`. For instance, a combo box with 600 items went form a paint time of 250ms to about 4 seconds. See https://github.com/vaadin/vaadin-combo-box/issues/526

**Comment by moderndeveloperllc** [comment]
@manolo The issue would seem to be with the `updateStyles()` (from PR #16) call that is now being made. This is updating the styles on every Vaadin element in the DOM - in my case on 600 `<vaadin-combo-box-item>` elements. Not sure the solution to this.

**Comment by manolo** [comment]
Have you the time to try to remove the line that update the styles (do it directly in your project bower_components folder) in order to verify that it fixes the problem (line 59 in the vaadin-themable-mixin) ? or it's necessary to remove all the code in the updateStyles method ?

**Comment by moderndeveloperllc** [comment]
@manolo The offending line actually appears to be [line 51](https://github.com/vaadin/vaadin-themable-mixin/blob/master/vaadin-themable-mixin.html#L51) which means this is probably an upstream issue. Line 56 also can take some time (15ms) since it's joining several hundred items.

**Comment by moderndeveloperllc** [comment]
If you want a jsbin that includes the data set I'm using: https://jsbin.com/nijaqev/edit?html,output

**Comment by jouni** [comment]
Ouch! Thanks for catching this so early 🙇 

This is clearly the usual case of setting something in the DOM that may affect layout/style and the immediately after forcing the browser to perform layout and style, and then doing that (recursively) for a lot of elements.

Not sure what would be our escape hatch for this: the `theme` attribute on a parent could set the CSS property on the child, and we should catch that somehow. We might have to reconsider this approach altogether, or then introduce some limitations how it can be used (for example that we don’t allow this to be used for the `vaadin-combo-box-item` element).

**Comment by moderndeveloperllc** [comment]
@jouni I do notice that the mixin isn't set up (yet) for grid items. That would have hit more people sooner as `vaadin-grid` can easily have hundreds of `vaadin-grid-cell-content` elements. I'm just glad y'all are serious about these web components. `vaadin-grid` and `vaadin-combo-box` are hands-down the best out there.

**Comment by jouni** [comment]
Thanks for the kind words! Yeah, I had to check grid yesterday as well, to see if it was affected.

@tomivirkki, I’m wondering the reason to use the mixin for `vaadin-combo-box-item` in the first place, or even having a separate custom element for it. Couldn’t we just have a named `part="item"` inside `vaadin-combo-box-overlay` (once we have that extension instead of the generic `vaadin-overlay`)?

**Comment by manolo** [comment]
So the performance issue is mainly due to the call to either method: `window.ShadyCSS.getComputedStyleValue` or `getComputedStyle(this).getPropertyValue` to compute the current value of `--theme` custom property.  Both force a expensive reflow in browser.

**Comment by platosha** [comment]
@moderndeveloperllc We have concluded that we can proceed without this feature for now.

I’ve unpublished `v1.2.0` until further research on the feature is done. Please downgrade your install to `v1.1.2`.

**Comment by moderndeveloperllc** [comment]
@platosha Thanks.

**Comment by misraelsen** [comment]
I am seeing this same behavior again...   I have 1,700 items in the combo and it takes 4 or 5 seconds to come back the first time type something that is not in the lookup.  Any idea on what could be causing it again.

**Comment by moderndeveloperllc** [comment]
@misraelsen Can you out up a Jsbin of your code? Feel free to use a copy of mine above to start it out. I’ve found Vaadin can fix things better if they have a concrete example to debug.
