### ISSUE TITLE
Enable browser-specific styles in theme modules

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/vaadin-themable-mixin#34]
Vaadin Framework had this great feature of generating class names to the UI's root element indicating the detected browser, e.g.` v-ie`, `v-ch`, `v-touch`, etc.

Flow seems to have inherited the browser detection from Framework, but no class names are generated. Furthermore, even if class names were generated, these would not be usable in theme modules.

Since IE11 support means there will still be a lot of browser-specific styling needed, it would be important to make this possible within theme modules.

Perhaps theme modules could have an additional attribute such as for-ua with which you could write browser-specific modules, e.g.
`<dom-module id="something" theme-for="vaadin-button" for-ua="ie edge">`

**Comment by web-padawan** [comment]
Discussed in vaadin/flow#2844

We should avoid browser workarounds as much as possible, but Lumo still has some of those.
@jouni should we somehow document it maybe? We have at least following ones:
```
@-moz-document url-prefix() {
  /* Firefox only */
}
```

```
::-ms-backdrop,
[part="checkbox"] {
  /* IE11 only */
}
```

**Comment by rolfsmeds** [comment]
We, as in our own themes, should certainly avoid workarounds, but we shouldn't expect our users to.

Sure, there's usually a way to style things so that it works across all browsers, but that can often require a lot more time and code to implement than simply writing an ie-specific style block.

Also, yes, there are non-vaadin-specific css tricks to target IE, but those are not as easy to use as the classnames were in Framework. I think the priority should be ease of use rather than purity.

Also, something like v-touch (i.e. touchscreen UAs) is not really a workaround but can be very useful for applying styling specific to touch or non-touch devices, such as providing alternatives to hover effects on touch devices. Keep in mind that we (afaik) cannot use media queries in theme modules (please correct me if I'm wrong).

**Comment by web-padawan** [comment]
Touch devices is a separate thing because of the MS Surface.
See 
vaadin/vaadin-grid/#1467
https://github.com/vaadin/vaadin-upload/issues/255#issuecomment-374156229

**Comment by jouni** [comment]
I’m quite much against this idea in general, as it goes against general web authoring best practices. 

But I do understand real-world situations sometimes require solutions rather than idealism, so I would suggest you use Flow to add these classes to your own application and then use CSS custom properties together with those for browser-specific styling. Right now that’s probably more work than what you’d like, but it’s certainly faster than waiting for an officially supported feature to appear.

Related issue in Flow: https://github.com/vaadin/flow/issues/2844

**Comment by web-padawan** [comment]
In the next generation components (where we drop IE11 support) we will aim to have as less workarounds as possible, but we would still have [`@vaadin/browser-utils`](https://github.com/vaadin/component-mixins/tree/master/packages/browser-utils) package.

Here is how it could be used in practice (note we don't yet have `isFirefox` there):

```js
import {registerStyles, css} from '@vaadin/vaadin-themable-mixin/register-styles.js';
import {isFirefox} from '@vaadin/browser-utils';

registerStyles('vaadin-component', css`
  /* styles for all browsers */
`);

if (isFirefox) {
  registerStyles('vaadin-component', css`
    /* styles for Firefox */
  `);
}
```

BTW, a very similar workaround is already used by [vaadin-grid styles](https://github.com/vaadin/vaadin-grid/blob/ea656c9e7527c256bce13b37efd97f8fa18498a2/src/vaadin-grid-styles.html#L312-L337).

As you can see, we can accomplish the request without a new API. So I'm closing this issue.
