### ISSUE TITLE
Document usage of theme attribute

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/vaadin-themable-mixin#47]
Theme attribute already propagates to themeable parts, but the Wiki could contain some examples of using this feature to style sub-parts.

**Comment by lkraav** [comment]
@OlliTietavainenVaadin did you already figure a few examples out on your own, or?

**Comment by OlliTietavainenVaadin** [comment]
Here is one: https://vaadin.com/forum/thread/17596415/17596439

**Comment by tomivirkki** [comment]
Also clarify the property description at: https://github.com/vaadin/vaadin-themable-mixin/blob/master/vaadin-theme-property-mixin.html#L16 Explain how the attribute propagates to all internally used components (that extend the mixin).

Remove the mention of templates and example on how to bind to attributes with Polymer syntax.
