### ISSUE TITLE
Include example of more complex styling

### ISSUE THREAD

**Issue by martinisraelsen** [vaadin/vaadin-themable-mixin#48]
It would be good to have a more complex example. For example restyling a combo box or select completely. These have text, a button/icon and overlay. Ideally change textfield background color, text field color, icon and font-size.

**Comment by web-padawan** [comment]
The updated documentation with some more styling examples can be found here:
https://vaadin.com/docs/v14/themes/styling-components.html

Closing. We will update the README to link to these docs.
