### ISSUE TITLE
Version 1.5.0 breaks styles of some components

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-themable-mixin#65]
Yesterday 1.5.0 got released, and themes of many components broke. For example:

<img width="288" alt="Screenshot 2019-10-04 at 18 51 28" src="https://user-images.githubusercontent.com/851745/66252598-d00d0600-e75d-11e9-8e26-7179453744a3.png">

here `vaadin-button` is okay, but `vaadin-password-field` lost its style;

<img width="347" alt="Screenshot 2019-10-04 at 16 46 47" src="https://user-images.githubusercontent.com/851745/66252617-e74bf380-e75d-11e9-8c34-f045fb861c66.png">

here `vaadin-combo-box` is okay, but `vaadin-select` lost its style.

Being 1.5.0 a minor release, it gets installed automatically via `npm`. Workaround: pin it at 1.4.4 with

```
npm install @vaadin/vaadin-themable-mixin@1.4.4
```

See also: https://github.com/vaadin/flow/issues/6626

**Comment by web-padawan** [comment]
Most likely related to #53
Will revert today and release 1.5.1

**Comment by web-padawan** [comment]
Just released 1.5.1
Closing this issue. Will investigate what was wrong with #53  later.
