### ISSUE TITLE
Feature request: add API for using Polymer style modules in LitElement

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-themable-mixin#73]
As discussed internally, there is a need to reuse CSS from Lumo in LitElement components.

While we can use `registerStyles` to achieve that, we don't want our users to use `ThemableMixin` in their own custom components. The preferable way would be to use `static get styles()`.

Here is a [snippet](https://github.com/vaadin/starter-wizard/blob/6a8238088423796316c5f17991ec81881525da6f/frontend/src/views/template/styles/lumo.ts#L9-L17)currently used in Starter Wizard view to workaround that:

```ts
const getStyleModule = (id: string): CSSResult => {
  const template: HTMLTemplateElement | null = DomModule.import(id, 'template') as HTMLTemplateElement;
  let cssText =
    template &&
    stylesFromTemplate(template, '')
      .map((style: HTMLStyleElement) => style.textContent)
      .join(' ');
  return unsafeCSS(cssText);
};
```

The possible example proposed by @manolo:

```js
import styles from '../styles/views/dashboard/dashboard-view.css';
import {CSSModule} from '../styles/utils.ts';

....
  static get styles() {
    return [
      CSSModule('lumo-typography'),
      CSSModule('lumo-badge'),
      unsafeCSS(styles)
    ];
  }
```

It seems like this repo would be a proper place to put this API, alongside with `registerStyles`. The name `getStyleModule` / `CSSModule` is something to discuss.

**Comment by lkraav** [comment]
> Here is a snippetcurrently used in Starter Wizard view to workaround that:

Snippet links 404s, is it a private repo?

**Comment by web-padawan** [comment]
Sorry, that is private repo indeed. The snippet is actually this one: https://github.com/web-padawan/lit-components/blob/master/packages/polymer-style-module/polymer-style-module.js

**Comment by jouni** [comment]
IMO we should refactor the theme ES modules to export the styles, in addition to registering the legacy Polymer style module.

E.g. sizing.js

```javascript
export const styles = css`
  html {
      --lumo-size-xs: 1.625rem;
      --lumo-size-s: 1.875rem;
      --lumo-size-m: 2.25rem;
      --lumo-size-l: 2.75rem;
      --lumo-size-xl: 3.5rem;
      /* Icons */
      --lumo-icon-size-s: 1.25em;
      --lumo-icon-size-m: 1.5em;
      --lumo-icon-size-l: 2.25em;
      /* For backwards compatibility */
      --lumo-icon-size: var(--lumo-icon-size-m);
    }
`;

const $_documentContainer = document.createElement('template');
$_documentContainer.innerHTML = `<custom-style><style>${styles}</style></custom-style>`;

document.head.appendChild($_documentContainer.content);
```

**Comment by jouni** [comment]
If the side-effect of adding the styles to the global scope is deemed unwanted, we could add an additional file that only exports the CSS string and keep the old files for the side-effect.

E.g. `vaadin-lumo-styles/modules.js`:
```js

export const sizingProps = css`
      --lumo-size-xs: 1.625rem;
      --lumo-size-s: 1.875rem;
      --lumo-size-m: 2.25rem;
      --lumo-size-l: 2.75rem;
      --lumo-size-xl: 3.5rem;
      /* Icons */
      --lumo-icon-size-s: 1.25em;
      --lumo-icon-size-m: 1.5em;
      --lumo-icon-size-l: 2.25em;
      /* For backwards compatibility */
      --lumo-icon-size: var(--lumo-icon-size-m);
`;

export const typographyProps = css`
      /* Font families */
      --lumo-font-family: -apple-system, BlinkMacSystemFont, "Roboto", "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";

      /* Font sizes */
      --lumo-font-size-xxs: .75rem;
      --lumo-font-size-xs: .8125rem;
      --lumo-font-size-s: .875rem;
      --lumo-font-size-m: 1rem;
      --lumo-font-size-l: 1.125rem;
      --lumo-font-size-xl: 1.375rem;
      --lumo-font-size-xxl: 1.75rem;
      --lumo-font-size-xxxl: 2.5rem;

      /* Line heights */
      --lumo-line-height-xs: 1.25;
      --lumo-line-height-s: 1.375;
      --lumo-line-height-m: 1.625;
`;

export const typography = css`
      :root,
      :host {
        font-family: var(--lumo-font-family);
        font-size: var(--lumo-font-size, var(--lumo-font-size-m));
        line-height: var(--lumo-line-height-m);
        -webkit-text-size-adjust: 100%;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
      }

      h1,
      h2,
      h3,
      h4,
      h5,
      h6 {
        font-weight: 600;
        line-height: var(--lumo-line-height-xs);
        margin-top: 1.25em;
      }

      h1 {
        font-size: var(--lumo-font-size-xxxl);
        margin-bottom: 0.75em;
      }
   
      ...
`;
```


The `css` tagged template probably doesn’t work nicely with strings without selectors, though, and some further thinking is needed there.

**Comment by jouni** [comment]
Coming back to this, there should actually be any need to create the JS modules manually (which I proposed earlier). 

We could simply rely on build tools, like webpack and css-loader, to handle the transformation for us. We should simply have plain css files in vaadin-lumo-styles (and material-styles). 

Though, we would still need Polymer style modules for backwards compat, and I’m not sure if there’s a clean way to make that happen without copy-pasting the styles.

**Comment by web-padawan** [comment]
> We could simply rely on build tools, like webpack and css-loader, to handle the transformation for us

Would this mean that we officially recommend using our components with webpack?

**Comment by jouni** [comment]
My mind was thinking about this mainly in the context of a Vaadin-app, where webpack is given. So, yeah, you have a point, that we would likely still want to support projects without a build step.

**Comment by web-padawan** [comment]
Decided to go with the approach suggested by https://github.com/vaadin/vaadin-themable-mixin/issues/73#issuecomment-562149495

So now we have the following issues where this can be tracked:
- Lumo: https://github.com/vaadin/vaadin-lumo-styles/issues/90
- Material: https://github.com/vaadin/vaadin-material-styles/issues/100
- Components: https://github.com/vaadin/vaadin-core/issues/264

Closing in favor of these issues.
